
import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react'
import { IMonsters } from '../models/monster.model'

export const monstersApi = createApi({
  reducerPath: 'monstersApi',
  // cache tags generated by this slice
  tagTypes: ['monstersApi'],
  baseQuery: fetchBaseQuery({ baseUrl: 'https://botw-compendium.herokuapp.com/api/v3/compendium/' }),
  endpoints: (build) => ({
    getAllMonsters: build.query<IMonsters, void>({
      query: () => `category/monsters`,
      // generate a cache tag for this query (populate this cache)
      providesTags: ['monstersApi'],
      // used in case of mutations to invalidate the cache
      // invalidatesTags: ['Post'],
    }),
  }),
})

// Export hooks for usage in function components, which are
// auto-generated based on the defined endpoints
export const { useGetAllMonstersQuery } = monstersApi
