import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';
import { Monster } from '../models/monster.model';
import { IApiResponse } from './types';
import { Material } from '../models/material.model';

export const zeldaApi = createApi({
  reducerPath: 'zeldaApi',
  // cache tags generated by this slice
  tagTypes: ['monsters', 'materials'],
  baseQuery: fetchBaseQuery({
    baseUrl: 'https://botw-compendium.herokuapp.com/api/v3/compendium/',
  }),
  endpoints: build => ({
    getAllMonsters: build.query<IApiResponse<Monster>, void>({
      query: () => `category/monsters`,
      // generate a cache tag for this query (populate this cache)
      providesTags: ['monsters'],
      // used in case of mutations to invalidate the cache
      // invalidatesTags: ['Post'],
    }),
    getAllMaterials: build.query<IApiResponse<Material>, void>({
      query: () => `category/materials`,
      providesTags: ['materials'],
    }),
  }),
});

// Export hooks for usage in function components, which are
// auto-generated based on the defined endpoints
export const { useGetAllMonstersQuery, useGetAllMaterialsQuery } = zeldaApi;
